# Generated by Django 4.2.13 on 2024-07-02 05:24

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking_hotel_address_hotel_description_hotel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
